# Generated by Django 5.2.6 on 2025-09-30 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('beer', 'Beer'), ('wine', 'Wine'), ('spirits', 'Spirits & Liquor'), ('cocktail', 'Cocktails'), ('soft_drink', 'Soft Drinks'), ('juice', 'Juices'), ('hot_beverage', 'Hot Beverages'), ('mocktail', 'Mocktails')], default='spirits', max_length=20)),
                ('alcohol_content', models.CharField(blank=True, help_text='e.g., 40% ABV, Non-alcoholic', max_length=50, null=True)),
                ('volume', models.CharField(blank=True, help_text='e.g., 330ml, 750ml, 1 glass', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bar/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide this item from the bar menu')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items appear prominently on the bar page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bar Item',
                'verbose_name_plural': 'Bar Items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
