# Generated by Django 5.2.7 on 2025-10-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baritem',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a direct image URL (e.g. Unsplash)', max_length=500, null=True),
        ),
    ]
