name: Auto-migrate on push to main

on:
  push:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DJANGO_SETTINGS_MODULE: hotel_app.settings
      DEBUG: 'False'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show migration plan
        if: env.DATABASE_URL != ''
        run: |
          python manage.py showmigrations
      - name: Run migrations (if DATABASE_URL is set)
        if: env.DATABASE_URL != ''
        run: |
          python manage.py migrate --noinput
      - name: Create superuser (optional)
        if: env.DATABASE_URL != '' && env.DJANGO_SUPERUSER_USERNAME != '' && env.DJANGO_SUPERUSER_PASSWORD != ''
        env:
          DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        run: |
          python manage.py createsuperuser --noinput || echo "Superuser may already exist"
      - name: Skip notice (no DATABASE_URL)
        if: env.DATABASE_URL == ''
        run: |
          echo "DATABASE_URL secret not set; skipping migrations. Add it in GitHub → Settings → Secrets → Actions."
