name: Run Django migrations (manual)

on:
  workflow_dispatch:
    inputs:
      database_url:
        description: "DATABASE_URL for production database"
        required: true
        type: string

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        env:
          DATABASE_URL: ${{ inputs.database_url }}
          DJANGO_SETTINGS_MODULE: hotel_app.settings
          DEBUG: 'False'
        run: |
          python manage.py migrate --noinput
